version: '3.3'

services:
  django-backend:
    depends_on: [ mysql-server ]
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
    - .:/app
    ports:
    - "8000:8000"

    environment:
      DB_NAME: dev_db
      DB_HOST: mysql-server
      DB_USER: dev_user
      DB_PASSWORD: dev_pass

      AWS_S3_ENDPOINT_URL: http://hb.bizmrg.com/
      AWS_STORAGE_BUCKET_NAME: miptoverflow
      AWS_ACCESS_KEY: quZTPp3V28P7V1SGJRXxvs
      AWS_SECRET_KEY: 7arUgwahLMmhHpreUJh9RTkHB7LdD5UNcTjA5VLSP59G

  mysql-server:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
    - .db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: dev_root_pass
      MYSQL_DATABASE: dev_db
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: dev_pass

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
    - 8080:8080
    links:
    - django-backend
    - centrifugo
    environment:
      AWS_S3_ENDPOINT_URL: http://hb.bizmrg.com/
      AWS_STORAGE_BUCKET_NAME: miptoverflow
      AWS_ACCESS_KEY: quZTPp3V28P7V1SGJRXxvs
      AWS_SECRET_KEY: 7arUgwahLMmhHpreUJh9RTkHB7LdD5UNcTjA5VLSP59G

  centrifugo:
    image: centrifugo/centrifugo:latest
    command: centrifugo -c /centrifugo/centrifugo.json --port=9000 --admin
    volumes:
    - ./conf/centrifugo.json:/centrifugo/centrifugo.json
    restart: always
    ports:
      - 9000:9000

    ulimits:
      nofile:
        soft: 65536
        hard: 65536
